FROM openjdk:17-alpine

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apk update \
  && apk add --no-cache \
    ca-certificates \
    curl \
    unzip \
    bash

RUN addgroup -g ${GROUP_ID} app \
  && adduser -u ${USER_ID} -G app -h /home/app -S -D app \
  && mkdir /app && chown -R app:app /app \
  && mkdir /home/app/.m2 && chown -R app:app /home/app/.m2

RUN curl -s https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz | tar xvz -C /opt \
  && mv /opt/apache-maven-* /opt/maven

RUN curl -s -L https://repo.spring.io/artifactory/release/org/springframework/boot/spring-boot-cli/2.7.0/spring-boot-cli-2.7.0-bin.tar.gz | tar xvz -C /opt \
  && mv /opt/spring-* /opt/spring

RUN curl -s -L https://services.gradle.org/distributions/gradle-7.4.2-bin.zip | busybox unzip -d /opt - \
  && mv /opt/gradle-* /opt/gradle

ENV PATH="$PATH:/opt/spring/bin:/opt/maven/bin:/opt/gradle/bin"
ENV M2_HOME=/home/app/.m2

USER app

WORKDIR /app